/**
 * War relevance keywords — copied verbatim from the original `WAR_KEYWORDS`.
 * The original compared lowercase headline words against this set, so "ICBM" could never
 * match; the set is lowercased at build time here (minimal fix, list unchanged).
 */
const RAW_WAR_KEYWORDS = [
  "strike",
  "attack",
  "missile",
  "bomb",
  "troops",
  "killed",
  "casualties",
  "invasion",
  "offensive",
  "drone",
  "airstrike",
  "shelling",
  "combat",
  "battle",
  "war",
  "military",
  "weapon",
  "nuclear",
  "rocket",
  "artillery",
  "navy",
  "warship",
  "fighter",
  "jet",
  "intercept",
  "shoot",
  "fire",
  "deploy",
  "raid",
  "siege",
  "blockade",
  "sanctions",
  "embargo",
  "convoy",
  "base",
  "frontline",
  "advance",
  "retreat",
  "captured",
  "destroy",
  "launch",
  "ICBM",
  "ballistic",
  "cruise",
  "tank",
  "infantry",
  "brigade",
  "battalion",
  "division",
  "regiment",
  "wounded",
  "dead",
  "hostage",
  "ceasefire",
  "violation",
  "escalation",
  "provocation",
  "incursion",
  "airspace",
  "territorial",
  "shell",
  "mortar",
  "grenade",
  "sniper",
  "ambush",
  "checkpoint",
  "fortify",
  "bunker",
  "trench",
  "satellite",
  "reconnaissance",
  "surveillance",
  "cyber",
  "hack",
  "infrastructure",
  "enrichment",
  "uranium",
  "centrifuge",
  "warhead",
  "arsenal",
  "carrier",
  "submarine",
  "fleet",
  "patrol",
  "intercontinental",
] as const;

export const WAR_KEYWORDS: ReadonlySet<string> = new Set(
  RAW_WAR_KEYWORDS.map((w) => w.toLowerCase()),
);

/** A headline must contain at least this many war keywords. */
export const MIN_WAR_HITS = 2;

/** "Talk only" detector (section 7.5 item 4) — identical to the original regexes. */
export const TALK_ONLY_RE =
  /\b(says|said|warns|warned|urged|called for|expressed concern|discussed|announced plan|proposed|considers)\b/;
export const ACTION_RE = /\b(strike|attack|launch|fire|kill|destroy|intercept|deploy|shell|bomb)\b/;
