import { chromium } from "@playwright/test";
const [,, url, out, w, h, waitMs] = process.argv;
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: Number(w), height: Number(h) }, deviceScaleFactor: 1 });
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
page.on("pageerror", (e) => errors.push(String(e)));
await page.goto(url, { waitUntil: "networkidle" });
await page.waitForTimeout(Number(waitMs ?? 1500));
await page.screenshot({ path: out, fullPage: true });
console.log(JSON.stringify({ url, errors }));
await browser.close();
